todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('todolist/', include('todolistapp.urls')),
    path('admin/', admin.site.urls),
]

todolist/todolistapp/urls.py
from django.urls import path

from . import views

app_name="todolistapp"
urlpatterns = [
    path('', views.top),
    path('list/', views.showtasklist, name='list'),
    path('new/', views.makenewtask, name='new'),
    path('register/',views.registertask, name='reg'),
    path('delete/<int:pk>/', views.deletetask, name='del'),
    path('edit/<int:pk>/',views.edittask, name='edit'),
    path('view/<int:pk>/',views.viewtask, name='view'),

]

todolist/todolistapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    taskname=models.CharField(max_length=128)
    deadline=models.DateTimeField()
    priority=models.IntegerField()
    do_repeat=models.BooleanField()
    interval=models.DurationField(blank=True,null=True)
    interval_type=models.IntegerField()
    parent=models.ForeignKey("self",on_delete=models.CASCADE,blank=True,null=True)

todolist/todolistapp/views.py
from django.shortcuts import render,get_object_or_404
import django.http as http
from django.urls import reverse
from todolistapp.models import Task
from todolistapp.customutil import checkdue
import datetime
from dateutil.relativedelta import relativedelta


#
class InvalidValueError(Exception):
    def __init__(self,msg):
        self.msg=msg

#
prop_keys=["id","taskname","deadline","priority","do_repeat","interval_type","interval","parent"]



# Create your views here.
def top(req):
    # ?
    return http.HttpResponseRedirect(reverse('todolistapp:list'))
    
def showtasklist(req):
    tasks=Task.objects.all()
    t_overdue,t_intime,n=checkdue(tasks)
                
                
    return render(req,'todolistapp/tasklist.html',{'t_overdue':t_overdue, 't_intime':t_intime, 'n_overdue':n})

def makenewtask(req):
    # show task registration form
    tasks=Task.objects.all()
    t_overdue,t_intime,n=checkdue(tasks)

    prop_values=[-1,"",None,0,False,-1,"",-1]
    msg=req.GET['msg'] if 'msg' in req.GET else None
    page={"title":"Create","msg":msg}
    context={prop_keys[i]:prop_values[i] for i in range(len(prop_keys))}
    
    return render(req, 'todolistapp/newtask.html',{'t_overdue':t_overdue, 't_intime':t_intime, 'n_overdue':n, 'page':page, 'context':context})

def registertask(req):
    # register task
    now=datetime.datetime.now().astimezone()
    tz=now.tzinfo
    keys=["dl_y","dl_mon","dl_d","dl_h","dl_min"]
    try:
        pk=int(req.POST['pk'])
        if pk!=-1 and pk<1 :raise InvalidValueError("Invalid value(1)")
        
        taskname=req.POST['taskname']
        if taskname=="":raise InvalidValueError("TaskName cannot be empty.")
        
        deadline=datetime.datetime(*map(int,[req.POST[k] for k in keys]),tzinfo=tz)
        if deadline<now:raise InvalidValueError("Deadline should be after current time.")
        
        priority=int(req.POST['priority'])
        if not 0<=priority<=3:raise InvalidValueError("Invalid value(2)")

        do_repeat='repeat' in req.POST

        interval_type=int(req.POST['itvltype'])
        if not -1<=interval_type<=3:raise InvalidValueError("Invalid value(3)")
        
        days=0
        if do_repeat and interval_type==-1 :
            days=int(req.POST['interval'])
            if days<1:raise InvalidValueError("Interval should be positive integer.")

        pid=int(req.POST['parent'])
        if pid!=-1 and not Task.objects.filter(pk=pid).exists():raise InvalidValueError("Invalid value(4)")

        
        prop={
            'taskname': taskname,
            'deadline': deadline,
            'priority': priority,
            'do_repeat':do_repeat,
            'interval_type':interval_type,
            'interval':datetime.timedelta(days=days) if days else None,
            'parent':Task.objects.get(pk=pid) if pid!=-1 else None,
            }
            
        if pk!=-1: Task.objects.update_or_create(pk=pk,defaults=prop)
        else:Task(**prop).save()

        return http.HttpResponseRedirect(reverse("todolistapp:list"))
    except (KeyError,TypeError,ValueError) as e:
        # invalid form
        return http.HttpResponseRedirect(reverse("todolistapp:new"))
    except InvalidValueError as e:
        return http.HttpResponseRedirect("%s?msg=%s"%(reverse("todolistapp:new"),e.msg))
            

def deletetask(req,pk):
    # delete task
    Task.objects.filter(pk=pk).delete()
    return http.HttpResponseRedirect(reverse("todolistapp:list"))

def edittask(req,pk):
    tasks=Task.objects.all()
    t_overdue,t_intime,n=checkdue(tasks,pk)

    t=Task.objects.get(pk=pk)
    page={"title":"Edit",}
    
    context={k:getattr(t,k) for k in prop_keys}
    context["deadline"]=context["deadline"].astimezone()

    return render(req, 'todolistapp/newtask.html',{'t_overdue':t_overdue, 't_intime':t_intime, 'n_overdue':n, 'page':page, 'context':context})

def viewtask(req,pk):
    task=get_object_or_404(Task,pk=pk)
    now=datetime.datetime.now().astimezone()
    limit=task.deadline.astimezone()
    delta=limit-now

    return render(req, 'todolistapp/viewtask.html',{'task':task,'delta':delta})

todolist/todolistapp/templates/todolistapp/navbar.html
{% load customtags %}
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="#">To-do List</a>
	<!--
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>
    -->
    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
            {% disp_notify %}
        </li>
    </ul>
</nav>

todolist/todolistapp/templates/todolistapp/notify.html
<a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {% if n > 0 %}
    <span class="badge badge-pill badge-danger">{{ n }}</span>
    {% endif %}
    <i class="fas fa-bell fa-fw"></i>
</a>

<div class="dropdown-menu dropdown-menu-left" aria-labelledby="alertsDropdown">
    {% for t in t_overdue %}
        <a class="dropdown-item" href="{% url 'todolistapp:view' t.id %}"><span class="font-weight-bold text-danger">The deadline of {{ t.taskname }} has passed!</span>({{ t.deadline|date:"Y/m/d H:i" }})</a>
    {% empty %}
        <span class="dropdown-item">There is no notification.</span>
    {% endfor %}
</div>

todolist/todolistapp/templates/todolistapp/sidebar.html
<ul class="sidebar navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-folder"></i>
            <span>Manage Tasks</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                     <a class="dropdown-item" href="{% url 'todolistapp:list' %}">View Tasks</a>
            <a class="dropdown-item" href="{% url 'todolistapp:new' %}">New Task</a>
        </div>
    </li>
</ul>

todolist/todolistapp/templates/todolistapp/tasklist.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load customfilters %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Task List / To-do List</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'todolistapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'todolistapp/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'todolistapp/css/sb-admin.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    {% include 'todolistapp/navbar.html' %}

    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'todolistapp/sidebar.html' %}

        <div id="content-wrapper">

            <div class="container-fluid">



                <!-- DataTables Example -->
                {% if n_overdue %}
                <div class="card mb-3">
                    <div class="card-header">
                        <h2>OVERDUE Task List</h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="dataTable_od" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Task Name</th>
                                        <th>Deadline</th>
                                        <th>Priority</th>
                                        <th>Repeat</th>
                                        <th>Repeat Interval</th>
                                        <th>Parent Task</th>
                                        <th>Edit Task</th>
                                        <th>Delete Task</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for t in t_overdue %}
                                    <tr>
                                        <td><a href="{% url 'todolistapp:view' t.id %}">{{t.taskname}}</a></td>
                                        <td>{{t.deadline|date:"Y/m/d H:i"}}</td>
                                        <td>
                                            {% if t.priority == 0 %}
                                            Low
                                            {% elif t.priority == 1 %}
                                            Medium
                                            {% elif t.priority == 2 %}
                                            High
                                            {% elif t.priority == 3 %}
                                            Urgent
                                            {% endif %}
                                        </td>
                                        <td>{{t.do_repeat}}</td>
                                        <td>
                                            {% if not t.do_repeat %}
                                            N/A
                                            {% elif t.interval_type == -1 %}
                                            {% if t.interval %}{{t.interval|duration}}{% endif %}
                                            {% elif t.interval_type == 0 %}
                                            1 Week
                                            {% elif t.interval_type == 1 %}
                                            2 Weeks
                                            {% elif t.interval_type == 2 %}
                                            1 Month
                                            {% elif t.interval_type == 3 %}
                                            2 Month
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if t.parent == None %}
                                            N/A
                                            {% else %}
                                            {{t.parent.name}}
                                            {% endif %}
                                        </td>
                                        <td><a href="{% url 'todolistapp:edit' t.id %}"><Button class="btn btn-primary">Edit</Button></a></td>
                                        <td><a href="{% url 'todolistapp:del' t.id %}"><Button class="btn btn-danger">Delete</Button></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% endif %}
                <div class="card mb-3">
                    <div class="card-header">
                        <h2>Task List</h2>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>Task Name</th>
                                        <th>Deadline</th>
                                        <th>Priority</th>
                                        <th>Repeat</th>
                                        <th>Repeat Interval</th>
                                        <th>Parent Task</th>
                                        <th>Edit Task</th>
                                        <th>Delete Task</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for t in t_intime %}
                                    <tr>
                                        <td><a href="{% url 'todolistapp:view' t.id %}">{{t.taskname}}</a></td>
                                        <td>{{t.deadline|date:"Y/m/d H:i"}}</td>
                                        <td>
                                            {% if t.priority == 0 %}
                                            Low
                                            {% elif t.priority == 1 %}
                                            Medium
                                            {% elif t.priority == 2 %}
                                            High
                                            {% elif t.priority == 3 %}
                                            Urgent
                                            {% endif %}
                                        </td>
                                        <td>{{t.do_repeat}}</td>
                                        <td>
                                            {% if not t.do_repeat %}
                                            N/A
                                            {% elif t.interval_type == -1 %}
                                            {% if t.interval %}{{t.interval|duration}}{% endif %}
                                            {% elif t.interval_type == 0 %}
                                            1 Week
                                            {% elif t.interval_type == 1 %}
                                            2 Weeks
                                            {% elif t.interval_type == 2 %}
                                            1 Month
                                            {% elif t.interval_type == 3 %}
                                            2 Month
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if t.parent == None %}
                                            N/A
                                            {% else %}
                                            <a href="{% url 'todolistapp:view' t.parent.id %}">{{t.parent.taskname}}</a>
                                            {% endif %}
                                        </td>
                                        <td><a href="{% url 'todolistapp:edit' t.id %}"><Button class="btn btn-primary">Edit</Button></a></td>
                                        <td><a href="{% url 'todolistapp:del' t.id %}"><Button class="btn btn-danger">Delete</Button></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>



            </div>
            <!-- /.container-fluid -->

            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © sr_8e 2019</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'todolistapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'todolistapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'todolistapp/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'todolistapp/vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'todolistapp/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'todolistapp/js/sb-admin.min.js' %}"></script>

    <!-- Demo scripts for this page-->
    <script src="{% static 'todolistapp/js/demo/datatables-demo.js' %}"></script>

</body>

</html>

todolist/todolistapp/templates/todolistapp/viewtask.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load customfilters %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ task.taskname }} / To-do List</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'todolistapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'todolistapp/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'todolistapp/css/sb-admin.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    {% include 'todolistapp/navbar.html' %}

    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'todolistapp/sidebar.html' %}

        <div id="content-wrapper">

            <div class="container-fluid">

                <div class="card mb-3">
                    <div class="card-header">
                        <h2>{{ task.taskname }}</h2>
                    </div>
                    <div class="card-body">
                        <div>
                            <div class="row">
                                <label class="col-sm-2">Task Name</label>
                                <div class="col-sm-8">{{ task.taskname }}</div>
                            </div>
                            <div class="row">
                                {% with dl=task.deadline %}
                                    <label class="col-sm-2">DeadLine</label>
                                    <div class="col-sm-8">
                                        {{ task.deadline|date:"Y/m/d H:i" }}
                                        {% if delta.days < 0 %}(<span class='text-danger'>{{ delta|durabs|durtime }} Over</span> )
                                        {% else %}({{ delta|durtime }} Left )
                                        {% endif %}
                                    </div>
                                {% endwith %}
                            </div>
                            <div class="row">
                                <label class="col-sm-2">Priority</label>
                                <div class="col-sm-4">
                                    {% with pr=task.priority %}
                                        {% if pr == 0 %}Low
                                        {% elif pr == 1 %}Medium
                                        {% elif pr == 2 %}High
                                        {% elif pr == 3 %}Urgent
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2">Repeat</label>
                                <div class="col-sm-8">{{ task.do_repeat }}</div>
                            </div>
                            <div class="row">
                                <label class="col-sm-2">Interval</label>
                                <div class="col-sm-4">
                                    {% with it=task.interval_type %}
                                        {% if not task.do_repeat %}N/A
                                        {% elif it == -1 %}{{ task.interval|duration }}
                                        {% elif it == 0 %}1 Week
                                        {% elif it == 1 %}2 Weeks
                                        {% elif it == 2 %}1 Month
                                        {% elif it == 3 %}2 Months
                                        {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                                
                            <div class="row">
                                <label class="col-sm-2">Parent Task</label>
                                <div class="col-sm-8" name="parent">
                                    {% if not task.parent %}N/A
                                    {% else %}<a href="{% url 'todolistapp:view' task.parent.id %}">{{ task.parent.taskname }}</a>
                                    {% endif %}
                                </div>
                            </div>
                            <a href="{% url 'todolistapp:edit' task.id %}"><button type="button" class="btn btn-primary">Edit</button></a>
                            <a href="{% url 'todolistapp:del' task.id %}"><button type="button" class="btn btn-danger">Delete</button></a>
                            

                        </div>
                    </div>
                </div>



            </div>
            <!-- /.container-fluid -->

            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © sr_8e 2019</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'todolistapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'todolistapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'todolistapp/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'todolistapp/vendor/jquery/jquery.validation.min.js' %}"></script>

    <!-- Page level plugin JavaScript-->
    <script src="{% static 'todolistapp/vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'todolistapp/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'todolistapp/js/sb-admin.min.js' %}"></script>

    <!-- Demo scripts for this page-->
    <script src="{% static 'todolistapp/js/demo/datatables-demo.js' %}"></script>

    
</body>

</html>